"use strict";
exports.__esModule = true;
exports.GLTFInterpolationType = exports.InterpolationType = exports.OldAnimationInterpolationIndex = exports.OldAnimationOutputBufferlengthIndex = exports.OldAnimationOutputBufferOffsetIndex = exports.OldAnimationOutputCountIndex = exports.OldAnimationOutputOffsetIndex = exports.OldAnimationInputBufferLengthIndex = exports.OldAnimationInputBufferOffsetIndex = exports.OldAnimationInputCountIndex = exports.OldAnimationInputOffsetIndex = exports.OldAnimationTargetIDIndex = exports.OldAnimationPropertyIDIndex = exports.EAnimationPropertyID = void 0;
var EAnimationPropertyID;
(function (EAnimationPropertyID) {
    EAnimationPropertyID[EAnimationPropertyID["Position"] = 0] = "Position";
    EAnimationPropertyID[EAnimationPropertyID["RotationQuaternion"] = 1] = "RotationQuaternion";
    EAnimationPropertyID[EAnimationPropertyID["Scaling"] = 2] = "Scaling";
    EAnimationPropertyID[EAnimationPropertyID["MainTexUScale"] = 3] = "MainTexUScale";
    EAnimationPropertyID[EAnimationPropertyID["MainTexVScale"] = 4] = "MainTexVScale";
    EAnimationPropertyID[EAnimationPropertyID["MainTexUOffset"] = 5] = "MainTexUOffset";
    EAnimationPropertyID[EAnimationPropertyID["MainTexVOffset"] = 6] = "MainTexVOffset";
    EAnimationPropertyID[EAnimationPropertyID["Alpha"] = 7] = "Alpha";
    EAnimationPropertyID[EAnimationPropertyID["MainColor"] = 8] = "MainColor";
    EAnimationPropertyID[EAnimationPropertyID["ort"] = 9] = "ort";
    EAnimationPropertyID[EAnimationPropertyID["per"] = 10] = "per";
    EAnimationPropertyID[EAnimationPropertyID["IsActive"] = 11] = "IsActive";
    EAnimationPropertyID[EAnimationPropertyID["Euler"] = 12] = "Euler";
    EAnimationPropertyID[EAnimationPropertyID["intensity"] = 13] = "intensity";
    EAnimationPropertyID[EAnimationPropertyID["lightdiffuse"] = 14] = "lightdiffuse";
    EAnimationPropertyID[EAnimationPropertyID["AlphaCutOff"] = 15] = "AlphaCutOff";
    EAnimationPropertyID[EAnimationPropertyID["cellId"] = 16] = "cellId";
    EAnimationPropertyID[EAnimationPropertyID["OpacityTexUScale"] = 17] = "OpacityTexUScale";
    EAnimationPropertyID[EAnimationPropertyID["OpacityTexVScale"] = 18] = "OpacityTexVScale";
    EAnimationPropertyID[EAnimationPropertyID["OpacityTexUOffset"] = 19] = "OpacityTexUOffset";
    EAnimationPropertyID[EAnimationPropertyID["OpacityTexVOffset"] = 20] = "OpacityTexVOffset";
    EAnimationPropertyID[EAnimationPropertyID["MaskCutoff"] = 21] = "MaskCutoff";
    EAnimationPropertyID[EAnimationPropertyID["MaskTexUScale"] = 22] = "MaskTexUScale";
    EAnimationPropertyID[EAnimationPropertyID["MaskTexVScale"] = 23] = "MaskTexVScale";
    EAnimationPropertyID[EAnimationPropertyID["MaskTexUOffset"] = 24] = "MaskTexUOffset";
    EAnimationPropertyID[EAnimationPropertyID["MaskTexVOffset"] = 25] = "MaskTexVOffset";
})(EAnimationPropertyID = exports.EAnimationPropertyID || (exports.EAnimationPropertyID = {}));
/// [动画属性ID, target, Input(byteOffset, count, bufferByteOffset, bufferLength), Output(byteOffset, count, bufferByteOffset, bufferLength), interpolation]
exports.OldAnimationPropertyIDIndex = 0;
exports.OldAnimationTargetIDIndex = 1;
exports.OldAnimationInputOffsetIndex = 2;
exports.OldAnimationInputCountIndex = 3;
exports.OldAnimationInputBufferOffsetIndex = 4;
exports.OldAnimationInputBufferLengthIndex = 5;
exports.OldAnimationOutputOffsetIndex = 6;
exports.OldAnimationOutputCountIndex = 7;
exports.OldAnimationOutputBufferOffsetIndex = 8;
exports.OldAnimationOutputBufferlengthIndex = 9;
exports.OldAnimationInterpolationIndex = 10;
// ["STEP", "LINEAR", "PICUBICSPLINE", "CUBICSPLINE"];
var InterpolationType;
(function (InterpolationType) {
    InterpolationType[InterpolationType["STEP"] = 0] = "STEP";
    InterpolationType[InterpolationType["LINEAR"] = 1] = "LINEAR";
    InterpolationType[InterpolationType["PICUBICSPLINE"] = 2] = "PICUBICSPLINE";
    InterpolationType[InterpolationType["CUBICSPLINE"] = 3] = "CUBICSPLINE";
})(InterpolationType = exports.InterpolationType || (exports.InterpolationType = {}));
var GLTFInterpolationType;
(function (GLTFInterpolationType) {
    GLTFInterpolationType[GLTFInterpolationType["LINEAR"] = 1] = "LINEAR";
    GLTFInterpolationType[GLTFInterpolationType["STEP"] = 2] = "STEP";
    GLTFInterpolationType[GLTFInterpolationType["CUBICSPLINE"] = 3] = "CUBICSPLINE";
    GLTFInterpolationType[GLTFInterpolationType["PICUBICSPLINE"] = 4] = "PICUBICSPLINE";
})(GLTFInterpolationType = exports.GLTFInterpolationType || (exports.GLTFInterpolationType = {}));
